apiVersion: v1
kind: Service
metadata:
  name: health-checker-auth-service
  namespace: health-checker-backend
spec:
  selector:
    app: health-checker-auth
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
