apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: health-checker-company-hpa
  namespace: health-checker-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: health-checker-company
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
