apiVersion: v1
kind: Service
metadata:
  name: health-checker-mongo
  namespace: health-checker-db
spec:
  selector:
    app: health-checker-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
