apiVersion: v1
kind: PersistentVolume
metadata:
  name: health-checker-mongo-pv
  namespace: health-checker-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/health-checker-db
