apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: health-checker-mongo-pvc
  namespace: health-checker-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
